model:
  object: CATEMBEDInterface
  batch_size: 64
  learning_rate: 0.001
  mp_dim: 11
  epochs: 100
  layers: 400-400-400-400-400
  optimizer: Adam
  loss: MSELoss
  embedding_dropout: 0.1
  dropout: 0.1
trainer:
  input_space: 1
  num_cv: 40
