model: 
  object: CATEMBEDInterface
initial_params: 
  optimizer: Adam
  loss: MSELoss
  epochs: 100
  learning_rate: 0.001
  batch_size: 128
  layers: 
    - 128
    - 64
  embedding_dropout: 0.0
  dropout: 0.0
search_space: 
  optimizer: Adam
  loss: MSELoss
  epochs: 100
  dropout: 
    l: 0.0
    u: 0.25 
    dtype: uniform
  embedding_dropout: 
    l: 0.0
    u: 0.25
    dtype: uniform
  learning_rate: 
    l: 0.00001
    u: 1.0 
    dtype: loguniform
   batch_size: 256
